#!/bin/bash
#copy file or directory to the same location on all nodes
if [ $# -lt 1 ]; then
	echo No argument
	exit
fi
f=$1

for  node in beta gamma delta epsilon zeta eta; do
	echo "${node}:"
	scp -r $f  $node:$(dirname $f)
done
